# Site settings
title: Aleksandr Kudashkin
description_1: 'System Administrator'
description: 'Full Stack Developer (Ruby on Rails/ReactJS)'
url: 'http://kudashkin.pro'
town: 'Montreal, Canada'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Aleksandr Kudashkin'
  email: alex@kudashkin.pro
  github_username: AleksandrKudashkin
  twitter_username: akudashkin
  facebook_username:
  linkedin_username: alexkudashkin

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
